#!/bin/bash
ROUTE_OUEST=800;
ROUTE_SUD=$((ROUTE_OUEST - 200))
ROUTE_EST=$((ROUTE_SUD + 300))
ROUTE_NORD=$((ROUTE_EST + ROUTE_SUD))
NB_KM_ROUTE_RAPIDE=0

if ((ROUTE_RAPIDE < ROUTE_EST)); then
NB_KM_ROUTE_RAPIDE=$ROUTE_EST
STRING_ROUTE_RAPIDE="a l'est"
fi

if ((ROUTE_RAPIDE < ROUTE_SUD)); then
NB_KM_ROUTE_RAPIDE=$ROUTE_SUD
STRING_ROUTE_RAPIDE="au sud"
fi

if ((ROUTE_RAPIDE < ROUTE_NORD)); then
ROUTE_RAPIDE=$ROUTE_NORD
STRING_ROUTE_RAPIDE="au nord"
fi  

echo "La route la plus rapide est la route $STRING_ROUTE_RAPIDE qui fait $NB_KM_ROUTE_RAPIDE KM" 