#!/bin/bash
ROUTE_EST=$((ROUTE_SUD + 300))
ROUTE_SUD=$((ROUTE_OUEST - 200))
ROUTE_NORD=$((ROUTE_EST + ROUTE_SUD))
ROUTE_RAPIDE=0

if ((ROUTE_RAPIDE < ROUTE_EST)); then
ROUTE_RAPIDE=$ROUTE_EST

if ((ROUTE_RAPIDE < ROUTE_SUD)); then
ROUTE_RAPIDE=$ROUTE_SUD

if ((ROUTE_RAPIDE < ROUTE_NORD))
ROUTE_RAPIDE=$ROUTE_NORD

echo "La route la plus rapide est : $ROUTE_RAPIDE" 